#172.16.0.30 -> ESSE É O IP DO SERVIDOR QUE ESTOU USANDO

spring.datasource.url=jdbc:mysql://172.16.0.30:3306/rdsb_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=rdsb
#SENHA DO BANCO

#PRESTE ATENÇÃO NO ESPAÇO DEPOIS DA SENHA, TIRE ESSE NEGÓCIO DAÍ
spring.datasource.password=gmSenai

#DEBUG QUERIES
spring.jpa.show-sql=True


#ESSES DOIS COMANDOS SERVE PARA DEIXAR O CÓDIGO SQL MAIS LEGÍVEL, FACILITANDO O PROCESSO DE DEBUG
# Deixa o SQL bonitinho e identado (fácil de ler)
spring.jpa.properties.hibernate.format_sql=true

# Mostra os valores reais que você passou nos filtros (os '?' do SQL)
logging.level.org.hibernate.orm.jdbc.bind=trace
